# Generated by Django 3.2.8 on 2021-10-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('coordinates', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=300)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('review', models.CharField(max_length=250)),
                ('balta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balti.balta')),
            ],
        ),
    ]
