# Generated by Django 3.2.8 on 2021-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balta',
            name='coordinates',
            field=models.IntegerField(),
        ),
    ]
