# Generated by Django 3.2.8 on 2021-10-20 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0002_alter_balta_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balta',
            options={'verbose_name': 'Balta', 'verbose_name_plural': 'Balti'},
        ),
        migrations.AlterModelOptions(
            name='recenzie',
            options={'verbose_name': 'Recenzie', 'verbose_name_plural': 'Recenzii'},
        ),
        migrations.AddField(
            model_name='recenzie',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Data adaugare'),
        ),
        migrations.AlterField(
            model_name='recenzie',
            name='review',
            field=models.CharField(max_length=250, verbose_name='Recenzie'),
        ),
        migrations.AlterField(
            model_name='recenzie',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='recenzie',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titlu'),
        ),
    ]
