# Generated by Django 3.2.8 on 2021-10-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0004_alter_recenzie_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzie',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data adaugare'),
        ),
    ]
