# Generated by Django 3.2.8 on 2021-10-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0007_judet'),
    ]

    operations = [
        migrations.AddField(
            model_name='balta',
            name='county',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='balti.judet'),
            preserve_default=False,
        ),
    ]
