# Generated by Django 3.2.8 on 2021-10-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0008_balta_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balta',
            name='distance',
        ),
    ]
