# Generated by Django 3.2.8 on 2021-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0009_remove_balta_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balta',
            name='page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
