# Generated by Django 3.2.8 on 2021-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0010_balta_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='balta',
            name='map_page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
