# Generated by Django 3.2.8 on 2021-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balti', '0011_balta_map_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judet',
            options={'verbose_name': 'Judet', 'verbose_name_plural': 'Judete'},
        ),
        migrations.RemoveField(
            model_name='balta',
            name='coordinates',
        ),
    ]
